spring:
  application:
    name: web-template-init
  session:
    timeout: 86400
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/web-template-init
    username: root
    password: root
server:
  port: 8080  
  servlet:
    context-path: /v1
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
global-config:
db-config:
  logic-delete-field: isDelete 
  logic-delete-value: 1 
  logic-not-delete-value: 0 
    
    
