spring:
  application:
    name: app-backend-template
  session:
    timeout: 86400
    store-type: redis
  redis:
    port: 6379
    host: localhost
    database: 0
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yupao
    username: root
    password: root
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
server:
  port: 8080
  servlet:
    context-path: /v1
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
global-config:
db-config:
  logic-delete-field: isDelete
  logic-delete-value: 1
  logic-not-delete-value: 0 
    
    
